# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  tiny_mce:
    my_settings_content:
      relative_urls: false,
      remove_script_host: true,
      width: 1000,
      height: 800,
      skin: "default",
      dialog_type: "modal",
      relative_urls: false,
      plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
      theme_advanced_buttons1: "bold,italic,underline,strikethrough,forecolor,formatselect,bullist,numlist,blockquote,undo,redo,link,unlink,anchor,image,sub,sup,charmap,media,fullscreen,code",
      theme_advanced_buttons1_add: "tinybrowser",
      theme_advanced_buttons2: "",
      theme_advanced_buttons3: "",
      theme_advanced_buttons4: "",
      theme_advanced_toolbar_location: "top",
      theme_advanced_toolbar_align: "left",
      theme_advanced_statusbar_location: "none",
      theme_advanced_resizing: false,
      paste_auto_cleanup_on_paste: true,
      theme: "advanced",
      file_browser_callback: "tinyBrowser"
    my_settings_description:
      relative_urls: false,
      remove_script_host: true,
      width: 1000,
      height: 300,
      skin: "default",
      dialog_type: "modal",
      relative_urls: false,
      plugins: "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
      theme_advanced_buttons1: "bold,italic,underline,strikethrough,forecolor,formatselect,bullist,numlist,blockquote,undo,redo,link,unlink,anchor,image,sub,sup,charmap,media,fullscreen,code",
      theme_advanced_buttons1_add: "tinybrowser",
      theme_advanced_buttons2: "",
      theme_advanced_buttons3: "",
      theme_advanced_buttons4: "",
      theme_advanced_toolbar_location: "top",
      theme_advanced_toolbar_align: "left",
      theme_advanced_statusbar_location: "none",
      theme_advanced_resizing: false,
      paste_auto_cleanup_on_paste: true,
      theme: "advanced",
      file_browser_callback: "tinyBrowser"


  sf_admin_dash:
    web_dir:                      /sfAdminDashPlugin
    image_dir:                    /sfAdminDashPlugin/images/icons/
    default_image:                config.png
    resize_mode:                  thumbnail
    site:                         My Site
    include_path:                 true
    include_jquery_no_conflict:   false
    logout:                       true
    login_route:                  @sf_guard_signin
    logout_route:                 @sf_guard_signout

  sf_admin_dash:
    categories:
      Users:
        items:
          Users Management:
            url:          users
            image:        users.png
            credentials:  [superadmin]
      Conent:
        items:
          Languages:
            url:          language
            image:        language.png
            credentials:  [superadmin]
          Categories:
            url:          category
            image:        categories.png
            credentials:  [superadmin]
          Articles:
            url:          article
            image:        addedit.png
            credentials:  [superadmin]


  email_notification:
    from_name: 'Blueprint project'
    from_email: 'blueprint@project.org'
    title: 'Registration notification'
    message: "You have ben registered in Blueprint project.\n\rYour password is %password% \n\r"