<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    public static function getCategories()
    {
        return Doctrine_Query::create()
            ->select('*')
            ->from('Category');
    }

    public static function getTreeCategories()
    {
        return Doctrine_Query::create()
        ->select('c1.*, c2.*')
        ->from('Category c1')
        ->addFrom('Category c2')
        ->where('c1.id=c2.parent_id')
        ->execute(array() , Doctrine_Core::HYDRATE_SCALAR);
    }
}