<?php

/**
 * ScrinshotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScrinshotTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScrinshotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Scrinshot');
    }
}