<?php

/**
 * sfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
    public function getUserAvatar($param = null)
    {
        if(is_null($this->getAvatar()) || ($this->getAvatar() == ""))
        {
            if(!is_null($param))
            {
                return "/images/avatar_default_".$param.".jpg";
            }
            else
            {
                return "/images/no_avatar.png";
            }
        }
        elseif(!is_null($param))
        {
            $image_file_name = explode(".", $this->getAvatar());

            return "/uploads/avatar/".$image_file_name[0]."_".$param.".".$image_file_name[1];
        }
        else
        {
            return '/uploads/avatar/'.$this->getAvatar();
        }
    }
}
