<?php

/**
 * VideoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Video');
    }

    public static function getVideos()
    {
        return Doctrine_Query::create()
            ->select('*')
            ->from('Video')
            ->where("is_converted = ?", false)
            ->addWhere("is_active = ?", false)
            ->execute();
    }

    public static function getConvertVideo()
    {
        return Doctrine_Query::create()
            ->select("*")
            ->from("Video")
            ->where("is_converted = ?", true)
            ->addWhere("is_edit = ?", false)
            ->execute();

    }
}