<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Video extends BaseVideo
{
    public function getScrinshot()
    {
        return Doctrine_Query::create()
            ->select('*')
            ->from('Scrinshot')
            ->where('video_id = ?', $this->getId())
            ->orderBy('id')
            ->limit(1)
            ->fetchOne();
    }
}
