<?php

/**
 * VideoRatingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoRatingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoRatingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VideoRating');
    }
}