<?php

/**
 * Video
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    blueprint
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Video extends BaseVideo
{
    public function getScrinshots()
    {
        return Doctrine_Query::create()
            ->select('*')
            ->from('Scrinshot')
            ->where('video_id = ?', $this->getId())
            ->orderBy('id')
            ->execute();
    }

    public function getVideoRating()
    {
        $query = Doctrine_Query::create()
            ->select('AVG(rating)')
            ->from('VideoRating')
            ->where('video_id = ?', $this->getId())
            ->execute(array(), Doctrine::HYDRATE_SINGLE_SCALAR);

        if($query>0)
        {
            return $query;
        }
        else
        {
            return 0;
        }
    }

    public function isVoting()
    {
        $query = Doctrine_Query::create()
            ->select("count(id)")
            ->from('VideoRating')
            ->where('video_id = ?', $this->getId())
            ->andWhere('user_cookie_id = ?', $_COOKIE['myCookie'])
            ->execute(array(), Doctrine::HYDRATE_SINGLE_SCALAR);

        if($query>0)
        {
            return true;
        }
        else
        {
            return 'false';
        }
    }

    public function getCreator()
    {
        return $this->getVideoCreator()->getFullName();
    }

    public function getScrinshot()
    {
        $query = Doctrine_Query::create()
            ->select('file')
            ->from('Scrinshot')
            ->where('video_id = ?', $this->getId())
            ->execute()->getFirst();

        return '/uploads/scrinshot/'.$query['file'];
    }
}
