<?php

/**
 * VideoCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VideoCategory');
    }
}