<?php

/**
 * VideoWatchingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoWatchingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoWatchingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VideoWatching');
    }

    public static function isWatching($video, $unique_user)
    {
        $query = Doctrine_Query::create()
            ->select('count(*)')
            ->from('VideoWatching')
            ->where('video_id = ?', $video->getId())
            ->andWhere('user_cookie_id = ?', $unique_user)
            ->fetchOne();
        if($query->count > 0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    public static function setWatching($video, $unique_user)
    {
        $obj = new VideoWatching();
        $obj->setUserCookieId($unique_user);
        $obj->setVideo($video);
        $obj->save();
    }
}