<?php

/**
 * YoutubeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class YoutubeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object YoutubeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Youtube');
    }
}