# Define any application specific rules to your models here
# such as routing, partials, etc.

MyIndex:
  models:
    Article:
      route: @article_view?id=%id%&sf_culture=%culture%
      partial: article/searchResult