# Define any application specific rules to your models here
# such as routing, partials, etc.

MyIndex:
  models:
    Video:
      route: /video_view/%video_id%
      partial: video_list/searchResult
