all:
  stylesheets:    [/flowplayer/style.css, main.css, jquery.fancybox-1.3.4.css, comment.css]
  javascripts:    [/flowplayer/flowplayer-3.2.6.min.js, /flowplaye/flowplayer.embed-3.0.3.min.js, /sfJqueryReloadedPlugin/js/jquery-1.7.1.min.js, jquery-ui-1.8.18.custom.min.js, jquery.fancybox-1.3.4.js, jquery.slides.js], jquery.fancybox-1.3.4.js