generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Video
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          video
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        user_id: {label: "Creator"}
        is_scrinshot: { label: 'scrinshot'}
      list:
        title: Videos
        display: [=title, description, VideoCreator, category, duration, is_active, is_scrinshot ]
      filter:
        display: [title, description, user_id, category_id, duration, is_active]
      form:
        class: AdminVideoForm
      edit:
        display: [title, description, user_id, category_id, is_active ]
      new:
        display: [title, description, user_id, category_id, is_active ]