# Define all the models in your project that you want indexed.

MyIndex:
  models:
    Video:
      fields:
        id: unindexed
        title:
          boost: 1.5
          type: text
        description:
          boost: 1.5
          type: text
        creator: text
        scrinshot: unindexed
        is_scrinshot: unindexed


  index:
    analyzer: utf8num
    #case_sensitive: off
    #mb_string: on