# Define all the models in your project that you want indexed.

MyIndex:
  models:
    Article:
      fields:
        id: unindexed
        title:              { type: text,  boost: 1.5}
        description:        { type: text }
        content:            { type: unstored }

  index:
    encoding: UTF-8
    cultures: [en, ru]
#    stop_words: [the, an, it]
#    short_words: 2
    analyzer: utf8num #text, textnum, utf8, or utf8num
    case_sensitive: off # on, off
    mb_string: on # on, off