default:
  stylesheets:    [main.css, /sfJqueryReloadedPlugin/css/ui-lightness/jquery-ui-1.8.2.custom.css]
  javascripts:    [/sfJqueryReloadedPlugin/js/jquery-1.7.1.min.js, jquery-ui-1.8.18.custom.min.js, field-validation.js, jquery.form.js]