generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          users
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id, first_name, last_name, email_address, username, is_active, is_super_admin, last_login, created_at]
      filter:
        display: [id, first_name, last_name, email_address, username, is_active, is_super_admin, last_login, created_at]
      form:
        class: sfGuardUserAdminForm
      edit:    ~
      new:     ~
