ActivationCode:
  columns:
    user_id:            { type: integer, notnull: true, unique: true }
    code:               { type: string(255), notnull: true }
  relations:
    sfGuardUser:        { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: ActivationCode }


Language:
  columns:
    name:               { type: string(255), notnull: true }
    is_active:          { type: boolean, default: true }

Category:
  columns:
    name:               { type: string(255), notnull: true }
    title:              { type: string(255), notnull: true }
    description:        { type: text, notnull: true }
  actAs:
    Timestampable: ~
    I18n:
      fields: [title, description]

Article:
  columns:
    name:               { type: string(255), notnull: true }
    title:              { type: string(255), notnull: true }
    description:        { type: text, notnull: true }
    content:            { type: text }
  actAs:
    Timestampable: ~
    Taggable: ~
    I18n:
      fields: [title, description, content]
    sfLuceneDoctrineTemplate: ~

ArticleCategory:
  columns:
    article_id:         { type: integer, notnull: true}
    category_id:        { type: integer, notnull: true}
  relations:
    Article:            { onDelete: CASCADE, local: article_id, foreign: id, foreignAlias: Article }
    Category:           { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: Category }

Video:
  columns:
    title:              { type: string(255), notnull: true }
    description:        { type: text, notnull: true }
    scrinshot:          { type: string(255), notnull: true }
    file:               { type: string(255), notnull: true }
    is_active:          { type: boolean, default: false }
    is_converted:       { type: boolean, default: false }
    is_edit:            { type: boolean, default: false }
    status:             { type: enum(11), values:['in_progress', 'complete', 'convert'], default: 'in_progress' }
    user_id:            { type: integer, unique: true }
  relations:
    sfGuardUser:        { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: sfGuardUser }
    Youtube:            { onDelete: CASCADE, local: id, foreign: video_id, foreignAlias: Youtube, type: one }

Youtube:
  columns:
    title:              { type: string(255), notnull: true }
    description:        { type: text, notnull: true }
    scrinshot:          { type: string(255), notnull: true }
    link_youtube:       { type: string(255), notnull: true }
    active:             { type: boolean, default: false }
    download:           { type: boolean, default: false }
    is_edit:            { type: boolean, default: false }
    user_id:            { type: integer, unique: true }
    video_id:           { type: integer, unique: true }
  relations:
    sfGuardUser:        { onDelete: CASCADE, local: user_id, foreign: id, foreignAlias: sfGuardUser }
    Video:            { onDelete: CASCADE, local: video_id, foreign: id, foreignAlias: Video, type: one }